name: zenith
description: "Your 30-day transformation programme."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  cloud_functions: any
  firebase_messaging: any
  firebase_storage: any

  # State Management
  provider: any

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: any
  flutter_svg: any
  lottie: any
  shimmer: any
  smooth_page_indicator: any
  fl_chart: any
  confetti: any
  flutter_animate: ^4.5.2
  cached_network_image: any

  # Image
  image_picker: any

  # Utilities
  intl: any
  uuid: any
  path_provider: any
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
